# Generated by Django 5.2.7 on 2025-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('fuera_stock', 'Fuera de stock'), ('inactivo', 'Inactivo')], default='disponible', max_length=20),
        ),
    ]
